#!/usr/bin/env python3
"""Generate the pvm64 backend's constants from the u64 backend's constants.

Reads `curve25519-dalek/src/backend/serial/u64/constants.rs` and rewrites
every `FieldElement51::from_limbs([a, b, c, d, e])` literal (five radix-2^51
limbs; value = sum(limb_i << 51*i)) into the corresponding
`FieldElement4x64::from_limbs([w0, w1, w2, w3])` literal (four little-endian
radix-2^64 limbs; value = sum(limb_i << 64*i)), leaving everything else
(structure, cfg attributes, doc comments, Scalar52 constants) intact.

The Scalar52 constants are reused verbatim: in the pvm64 backend,
`super::scalar::Scalar52` resolves to the u64 backend's scalar re-included
via `#[path = "../u64/scalar.rs"]`.

Usage (from the workspace root):

    python3 scripts/convert_constants_pvm64.py

which writes `curve25519-dalek/src/backend/serial/pvm64/constants.rs`.
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "curve25519-dalek/src/backend/serial/u64/constants.rs"
DST = REPO_ROOT / "curve25519-dalek/src/backend/serial/pvm64/constants.rs"

P = 2**255 - 19

GENERATED_NOTE = """\
// THIS FILE IS AUTOGENERATED from the u64 backend's constants by
// `scripts/convert_constants_pvm64.py`. Do not edit by hand; re-run the
// script instead.
"""

FROM_LIMBS_RE = re.compile(
    r"FieldElement51::from_limbs\(\[(?P<limbs>[^\]]*)\]\)", re.DOTALL
)


def convert_literal(match: re.Match, text: str) -> str:
    limbs = [int(part.strip(), 0) for part in match.group("limbs").split(",") if part.strip()]
    if len(limbs) != 5:
        raise ValueError(f"expected 5 radix-2^51 limbs, got {limbs}")
    value = sum(limb << (51 * i) for i, limb in enumerate(limbs))
    if value >= 2**256:
        raise ValueError(f"value out of range: {value}")
    wide = [(value >> (64 * i)) & (2**64 - 1) for i in range(4)]

    # Leading whitespace of the line the literal starts on.
    line_start = text.rfind("\n", 0, match.start()) + 1
    line = text[line_start:match.start()]
    indent = line[: len(line) - len(line.lstrip())]

    limbs_str = ",\n".join(f"{indent}    0x{w:016x}" for w in wide)
    return f"FieldElement4x64::from_limbs([\n{limbs_str},\n{indent}])"


def main() -> None:
    text = SRC.read_text()

    # Convert every FieldElement51::from_limbs literal to 4x64 limbs.
    out = []
    pos = 0
    count = 0
    for match in FROM_LIMBS_RE.finditer(text):
        out.append(text[pos:match.start()])
        out.append(convert_literal(match, text))
        pos = match.end()
        count += 1
    out.append(text[pos:])
    text = "".join(out)

    if "FieldElement51::from_limbs" in text:
        raise AssertionError("unconverted FieldElement51::from_limbs literal left behind")

    # Rewrite the remaining type-name occurrences (imports, annotations).
    text = text.replace("FieldElement51", "FieldElement4x64")

    # Insert the autogenerated-file note after the license header comment.
    marker = "//! This module contains backend-specific constant values"
    if marker not in text:
        raise AssertionError("doc-comment marker not found")
    text = text.replace(marker, GENERATED_NOTE + marker, 1)

    DST.write_text(text)

    # Normalize the (mostly-already-conforming) formatting.
    if shutil.which("rustfmt"):
        subprocess.run(["rustfmt", "--edition", "2021", str(DST)], check=True)
    else:
        print("warning: rustfmt not found; skipping formatting", file=sys.stderr)

    # Sanity check: EDWARDS_D.
    d = 37095705934669439343138083508754565189542113879843219016388785533085940283555
    expected = [0x75EB4DCA135978A3, 0x00700A4D4141D8AB, 0x8CC740797779E898, 0x52036CEE2B6FFE73]
    assert [(d >> (64 * i)) & (2**64 - 1) for i in range(4)] == expected
    assert f"0x{expected[0]:016x}" in text, "EDWARDS_D limb 0 not found in output"

    print(f"converted {count} FieldElement51::from_limbs literals -> {DST}")


if __name__ == "__main__":
    sys.exit(main())
